### PR TITLE
OK, print function and pytest updates, finally

### PR DESCRIPTION
**Pull request by everyday847**
Merge me before we drift any more!

### CODE REVIEW

**Comment by rhiju** [comment]
Andy -- some of the output does not look the same as current master; and everythign is *slower*!? 

For example if I run:

`time ./alphafold.py -s GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA  --mfe `

In current master  I get:

```
Parameters:  alphafold  version 0.171

Doing backtrack to get minimum free energy structure:
GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
(((((((..((((........)))).(((((.......))))).....(((((.......))))))))))))....     0.122394604272 [MFE]

sequence = GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
cutpoint = ---------------------------------------------------------------------------X
circle   =  False
Z = 1.0029783807e+13
dG = -18.4508530073

real	0m0.963s
user	0m0.788s
sys	0m0.051s
```

But with your pull-request  I get:
```
BIOCHEM-C02SL0WGG8WM:alphafold_devel rhiju$ time ./alphafold.py -s GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA  --mfe  
('Parameters: ', 'alphafold', ' version', '0.171')
()
Doing backtrack to get minimum free energy structure:
GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
('(((((((..((((........)))).(((((.......))))).....(((((.......))))))))))))....', '   ', 0.12239460427204527, '[MFE]')
()
sequence = GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
cutpoint = ---------------------------------------------------------------------------X
circle   =  False
Z = 1.0029783807e+13
dG = -18.4508530073

real	0m1.556s
user	0m1.496s
sys	0m0.025s
```
That's about a 60% loss in speed. I've noticed similar losses in speed if I use anaconda Python 2..14 instead of my Mac's (older) system Python 2.7.10 -- so perhaps are your changes forcing use of a different Python interpreter?

**Comment by everyday847** [comment]
One of my changes was to the shebang line (`#!/usr/bin/env python`) rather than (`#!/usr/bin/python`). That may have changed the interpreter. (That can be changed back; I didn't know that you actively preferred your system python for this.)

The parens are because I must have missed a `from __future__ import __print_function` in some file. I can track that down by running manually with a `python2`.

**Comment by everyday847** [comment]
My own time output now:

```time ./alphafold.py -s GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA  --mfe
Parameters:  alphafold  version 0.171

Doing backtrack to get minimum free energy structure:
GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
(((((((..((((........)))).(((((.......))))).....(((((.......))))))))))))....     0.122394604272 [MFE]

sequence = GCGGAUUUAGCUCAGUUGGGAGAGCGCCAGACUGAAGAUCUGGAGGUCCUGUGUUCGAUCCACAGAAUUCGCACCA
cutpoint = ---------------------------------------------------------------------------X
circle   =  False
Z = 1.0029783807e+13
dG = -18.4508530073
./alphafold.py -s  --mfe  0.81s user 0.08s system 33% cpu 2.704 total```

**Comment by everyday847** [comment]
Regression on both output formatting and speed repaired.

**Pull request merged**
